### ISSUE TITLE
Executables

### ISSUE THREAD

**Issue by SethGower** [shanedonburke/DotSlashNote#1]
It isn't really great practice to have executables and binary files tracked by git. The only thing that should be in the repo are source files, and licenses and documentation. The readme should contain instructions on how to build your app on different ecosystems. To allow for people who don't want to build it themselves, you should use the "Releases" feature, where you can attach zip files of pre-built binaries. 

Although you say this is a windows application, upon very quick inspection, it is an electron app. The benefit of electron is _that it is cross platform_. So if you just want to have the windows binaries in a release, and then instructions for *nix users to build it themselves, that is perfectly valid.

**Comment by shanedonburke** [comment]
Good point. I'll update the repo. Thanks!
